import { SignInButton, SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // Clerk user
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();
  // const { data, isLoading } = {data: [], isLoading: true};

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex w-screen flex-col items-center bg-stone-800 lg:max-w-4xl md:max-w-2xl">
        <div className="flex w-full justify-end px-8 py-4">
          {!user.isSignedIn ? (
            <SignInButton />
          ) : (
            <div className="flex gap-4 rounded-md border-b-4 border-b-slate-400 p-3">
              <UserButton />
              <SignOutButton />
            </div>
          )}
        </div>
        <div className="flex min-h-screen flex-col justify-center">
          {isLoading && <div className="m-auto h-1/2 w-full animate-ping text-center">🥳🥳🥳</div>}
          {data?.map((post) => (
            <div key={post.id} className="mb-2 rounded-md border-4 bg-gray-400 p-4 text-center text-3xl">
              {post.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
